[package]
name = "group_thing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wca_oauth = { path = "../wca_oauth" }
serde = "1.0"
serde_json = "1.0"
fixedbitset = "0.4.2"