[package]
name = "wca_scorecards_lib"
version = "0.8.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wca_oauth = { path = "../wca_oauth" }
scorecard_to_pdf = { path = "../scorecard_to_pdf" }
