[package]
name = "wca_scorecards_lib"
version = "1.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wca_oauth = { path = "../wca_oauth" }
scorecard_to_pdf = { path = "../scorecard_to_pdf" }
zip = "4.0.0"
